name: mahjong
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  google_fonts:
  freezed_annotation: ^2.4.1
  percent_indicator:
  go_router:
  flutter_riverpod: ^2.5.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  freezed: ^2.5.2
  build_runner: ^2.4.11
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/


  uses-material-design: true

